import { buildKbAsset, compileKbAsset, type KbAssetSpec } from './build-kb-asset'

/**
 * Builds the shipped coverage-ratchet asset out of the single tested source
 * (ADL 2026-07-13: gate-tooling logic lives in a tested module; ADR-023: it
 * ships as a GENERATED KB asset, not as a CLI command).
 *
 * The module imports only node builtins, so a single-file transpile is a
 * complete program — no bundler in the dependency tree.
 *
 * Output (both copies, kept byte-identical):
 *   - packages/knowledge-hub/dataset/.pair/knowledge/assets/coverage-ratchet.cjs  (shipped corpus)
 *   - .pair/knowledge/assets/coverage-ratchet.cjs                                 (pair's own installed copy)
 *
 * The committed assets are drift-guarded by
 * conformance/coverage-ratchet-asset.test.ts: editing either copy by hand —
 * or editing the source without regenerating — turns the gate red.
 *
 * The transpile itself is NOT here: it is `build-kb-asset.ts`, shared with the
 * second asset that needed it, so two shipped assets cannot be generated by two
 * slightly different compilers.
 */
export const RATCHET_ASSET: KbAssetSpec = {
  source: 'packages/knowledge-hub/src/tools/coverage-baseline-ratchet.ts',
  regenerateScript: 'ratchet:asset',
  targets: [
    'packages/knowledge-hub/dataset/.pair/knowledge/assets/coverage-ratchet.cjs',
    '.pair/knowledge/assets/coverage-ratchet.cjs',
  ],
}

export function compileRatchetAsset(sourceText: string): string {
  return compileKbAsset(sourceText, RATCHET_ASSET)
}

if (require.main === module) buildKbAsset(RATCHET_ASSET)
