import { mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import ts from 'typescript'

/**
 * The generic half of "a KB asset is a build output of a tested module".
 *
 * The pattern was introduced for the coverage ratchet (ADL 2026-07-13: gate-tooling logic
 * lives in a tested module; ADR-023: it ships as a GENERATED KB asset, not as a CLI
 * command). It is not ratchet-specific, and the second asset to need it — the Codex fan-out
 * helper — would otherwise have copied the transpile options and the header format. Both
 * builders now call the function below, so the two shipped assets cannot be generated by two
 * slightly different compilers.
 *
 * A source that qualifies imports node builtins ONLY: a single-file transpile is then a
 * complete program, and no bundler enters the dependency tree.
 */

export interface KbAssetSpec {
  /** Repo-relative path of the tested source. Named in the generated header. */
  readonly source: string
  /** The `pnpm --filter @pair/knowledge-hub <script>` that regenerates it. */
  readonly regenerateScript: string
  /** Repo-relative paths of the committed copies, kept byte-identical. */
  readonly targets: readonly string[]
}

function header(spec: KbAssetSpec): string {
  return (
    '// GENERATED FILE — do not edit.\n' +
    `// Source: ${spec.source}\n` +
    `// Regenerate: pnpm --filter @pair/knowledge-hub ${spec.regenerateScript}\n\n`
  )
}

/**
 * Transpiles one source to the CommonJS text the asset ships as.
 *
 * `removeComments` is not a size choice: the shipped corpus bans story-local acceptance
 * markers, and the sources' comments carry them for pair-internal review. Stripping every
 * comment is the rule that cannot be forgotten, where curating them would be.
 */
export function compileKbAsset(sourceText: string, spec: KbAssetSpec): string {
  const { outputText } = ts.transpileModule(sourceText, {
    compilerOptions: {
      module: ts.ModuleKind.CommonJS,
      target: ts.ScriptTarget.ES2022,
      importHelpers: false,
      removeComments: true,
    },
    fileName: spec.source.split('/').pop() ?? spec.source,
  })
  // Comment-stripping can leave a catch block EMPTY (`catch {}`) when its only content was a
  // comment — a lint violation in the shipped corpus. Give those blocks an explicit
  // deliberate-no-op statement.
  return (
    header(spec) +
    outputText.replace(/catch \{\s*\}/g, 'catch {\n    void 0 // deliberately ignored\n  }')
  )
}

// packages/knowledge-hub/src/tools -> repo root
const REPO_ROOT = join(__dirname, '../../../..')

/** Reads the spec's source and writes every committed copy. Returns what it wrote. */
export function buildKbAsset(spec: KbAssetSpec): string {
  const compiled = compileKbAsset(readFileSync(join(REPO_ROOT, spec.source), 'utf8'), spec)
  for (const target of spec.targets) {
    const absolute = join(REPO_ROOT, target)
    mkdirSync(dirname(absolute), { recursive: true })
    writeFileSync(absolute, compiled)
    console.log(`${spec.regenerateScript} → ${target}`)
  }
  return compiled
}
