packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@eslint/js': 9.34.0
  '@types/node': 24.3.0
  '@typescript-eslint/eslint-plugin': 8.41.0
  '@typescript-eslint/parser': 8.41.0
  dotenv: 17.2.1
  eslint: 9.34.0
  globals: 15.0.0
  prettier: 3.6.2
  typescript: 5.4.5
  vitest: 3.2.4

cleanupUnusedCatalogs: true
