packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@eslint/js': 9.34.0
  '@types/markdown-it': 14.1.2
  '@types/mdast': 3.0.15
  '@types/node': 24.3.0
  '@typescript-eslint/eslint-plugin': 8.41.0
  '@typescript-eslint/parser': 8.41.0
  '@vitest/coverage-v8': 3.2.4
  dotenv: 17.2.1
  eslint: 9.34.0
  globals: 15.0.0
  prettier: 3.6.2
  typescript: 5.4.5
  vitest: 3.2.4
  commander: 11.0.0
  turbo: 2.5.6
  chalk: 4.1.2
  fs-extra: 11.2.0
  markdown-it: 14.1.0
  mdast: 3.0.0
  remark-parse: 11.0.0
  unified: 11.0.5
  ts-node: 10.9.2
  vite-tsconfig-paths: 5.1.4
  husky: 8.0.0

cleanupUnusedCatalogs: true
