packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@changesets/cli': 2.29.7
  '@playwright/experimental-ct-react': ^1.50.0
  '@eslint/js': 9.34.0
  '@inquirer/prompts': 7.5.0
  '@testing-library/jest-dom': 6.6.3
  '@testing-library/react': 16.1.0
  '@types/adm-zip': 0.5.7
  '@types/markdown-it': 14.1.2
  '@types/mdast': 3.0.15
  '@types/mdx': 2.0.13
  '@types/node': 24.3.0
  '@types/react': 19.0.6
  '@types/react-dom': 19.0.6
  '@typescript-eslint/eslint-plugin': 8.41.0
  '@typescript-eslint/parser': 8.41.0
  '@vitejs/plugin-react': 4.3.4
  '@vitest/coverage-v8': 3.2.4
  adm-zip: 0.5.16
  autoprefixer: 10.4.20
  chalk: 4.1.2
  commander: 11.0.0
  dotenv: 17.2.1
  fumadocs-core: 14.7.7
  fumadocs-mdx: 11.10.1
  fumadocs-ui: 14.7.7
  eslint: 9.34.0
  eslint-plugin-jsx-a11y: 6.10.2
  eslint-plugin-react: 7.37.2
  eslint-plugin-react-hooks: 5.1.0
  globals: 15.0.0
  husky: 8.0.0
  jsdom: 25.0.1
  markdown-it: 14.1.0
  markdownlint-cli: 0.47.0
  next: ^15.3.3
  next-themes: 0.4.6
  mdast: 3.0.0
  posthog-js: ^1.350.0
  postcss: 8.4.49
  prettier: 3.6.2
  react: 19.0.0
  react-dom: 19.0.0
  remark-parse: 11.0.0
  tailwindcss: 3.4.17
  ts-node: 10.9.2
  turbo: 2.5.6
  typescript: 5.4.5
  unified: 11.0.5
  vite: 6.0.7
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.4

cleanupUnusedCatalogs: true
