packages:
  - apps/*
  - packages/*
  - tools/*

catalog:
  '@changesets/cli': 2.29.7
  '@eslint/js': 9.34.0
  '@types/adm-zip': 0.5.7
  '@types/markdown-it': 14.1.2
  '@types/mdast': 3.0.15
  '@types/node': 24.3.0
  '@typescript-eslint/eslint-plugin': 8.41.0
  '@typescript-eslint/parser': 8.41.0
  '@vitest/coverage-v8': 3.2.4
  adm-zip: 0.5.16
  chalk: 4.1.2
  commander: 11.0.0
  dotenv: 17.2.1
  eslint: 9.34.0
  globals: 15.0.0
  husky: 8.0.0
  markdown-it: 14.1.0
  markdownlint-cli: 0.47.0
  mdast: 3.0.0
  prettier: 3.6.2
  remark-parse: 11.0.0
  ts-node: 10.9.2
  turbo: 2.5.6
  typescript: 5.4.5
  unified: 11.0.5
  vite-tsconfig-paths: 5.1.4
  vitest: 3.2.4

cleanupUnusedCatalogs: true
