/**
 * COMMONMARK BLOCK STRUCTURE — the shared decision table, and the reason it is shared.
 *
 * Every row is github.com's own output for the SAME bytes, not a reading of the spec:
 *
 *   printf %s "<content>" > f.md
 *   jq -Rs '{text:.}' f.md > f.json
 *   gh api -X POST /markdown --input f.json
 *
 * `anchors` are the `id="user-content-…"` / `name="user-content-…"` attributes of that
 * response, in document order (BOTH attributes: github rewrites an explicit
 * `<a name="x">` to `name="user-content-x"`, and browsers still resolve `#x` to it).
 * `markdownBlocks` are its `highlight-text-md` <pre> bodies, tags stripped and entities
 * unescaped, one trailing newline restored.
 *
 * BOTH consumer suites run this ONE table:
 *   - apps/website  — `collectHeadingSlugs(content)` must equal `anchors`
 *   - knowledge-hub — `markdownFences(content)` must equal `markdownBlocks`
 *   - content-ops   — `readMarkdown`/`fencedBlocks`, the reader both of those sit on
 * so deleting a container rule from the reader reddens all three, instead of one gate
 * being fixed while the other keeps disagreeing with github.com. That is not
 * hypothetical: it is exactly what happened twice on this branch before the reader was
 * extracted (see the module header in `../markdown/commonmark-blocks.ts`).
 *
 * `readerBlocks`/`readerAnchors` appear ONLY where this reader knowingly diverges from
 * github.com, so the cap is on record instead of latent. ONE row carries one today.
 */
export interface CommonMarkBlockRow {
  /** Stable row id, so a failure names the shape and not an index. */
  readonly name: string
  /** What this row pins. */
  readonly why: string
  readonly content: string
  /** github.com's anchors for these bytes, in document order. */
  readonly anchors: readonly string[]
  /** github.com's fenced ```markdown block bodies for these bytes. */
  readonly markdownBlocks: readonly string[]
  /** Set only where this reader knowingly diverges from `markdownBlocks`. */
  readonly readerBlocks?: readonly string[]
  /** Set only where this reader knowingly diverges from `anchors`. */
  readonly readerAnchors?: readonly string[]
}

export const COMMONMARK_BLOCK_ROWS: readonly CommonMarkBlockRow[] = [
  {
    name: 'list-atx',
    why: 'an ATX heading inside a LIST ITEM is a heading — the shape 5 CHANGELOGs in this repo ship',
    content: '# Doc\n\n- # In List\n\n## Real\n',
    anchors: ['doc', 'in-list', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'list-atx-content',
    why: "a heading at the item's content column, one blank line down",
    content: '- item\n\n  # Deeper\n\n## Real\n',
    anchors: ['deeper', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'ordered-list-atx',
    why: "an ORDERED list item's content column",
    content: '1. # Ordered H\n\n## Real\n',
    anchors: ['ordered-h', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'list-wide-marker',
    why: '3 spaces after the marker: the content column moves with them',
    content: '-   # Wide Marker\n\n## Real\n',
    anchors: ['wide-marker', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'nested-list-atx',
    why: 'a heading in a NESTED list item',
    content: '- a\n  - ## Nested H\n\n## Real\n',
    anchors: ['nested-h', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'indented-code-doc',
    why: '4 spaces at document level is an indented code block, not a heading',
    content: '# Doc\n\n    # Not A Heading\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'indented-in-item',
    why: "...and 4 columns PAST the item's content column is one inside the item",
    content: '- item\n\n      # Not In Item\n\n## Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'bq-atx',
    why: 'an ATX heading inside a BLOCKQUOTE is a heading',
    content: '> ## Quoted\n\n## Real\n',
    anchors: ['quoted', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'bq-deep',
    why: 'blockquote nested twice: both markers are peeled',
    content: '> > ## Deep Quoted\n\n## Real\n',
    anchors: ['deep-quoted', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'list-bq-atx',
    why: 'a blockquote inside a LIST ITEM: the containers interleave, and peeling one kind first misses it',
    content: '- > ## Quoted In List\n\n## Real\n',
    anchors: ['quoted-in-list', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'html-div',
    why: 'a heading inside a raw <div> HTML block (§ 4.6 type 6) is NOT a heading — the phantom anchor a citation would 404 on',
    content: '# Doc\n\n<div>\n## InDiv\n</div>\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'html-comment',
    why: '...nor inside an HTML COMMENT (type 2)',
    content: '# Doc\n\n<!--\n## InComment\n-->\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'html-details-blank',
    why: '...but a BLANK LINE ends a type-6 block, so the heading under it is real again',
    content:
      '# Doc\n\n<details>\n<summary>s</summary>\n\n## InsideDetails\n\n</details>\n\n## Real\n',
    anchors: ['doc', 'insidedetails', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'html-anchor-alone',
    why: '`<a name>` followed by `</a>` is not a lone tag, so it is a paragraph — and github serves its anchor',
    content: '<a name="manual"></a>\n\n# Real\n',
    anchors: ['manual', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'html-script',
    why: 'a heading inside <script> (type 1) ends at </script>',
    content: '# Doc\n\n<script>\n## X\n</script>\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'setext-multiline',
    why: "a SETEXT heading's text is the WHOLE paragraph, not its last line",
    content: 'Some paragraph\nline two\n---\n',
    anchors: ['some-paragraphline-two'],
    markdownBlocks: [],
  },
  {
    name: 'setext-eq-multi',
    why: '...same under `===`',
    content: 'Para two\nline b\n===\n\n## Real\n',
    anchors: ['para-twoline-b', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'setext-bq',
    why: 'a multi-line setext heading inside a blockquote',
    content: '> Quoted para\n> line two\n> ---\n\n## Real\n',
    anchors: ['quoted-paraline-two', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'setext-after-atx',
    why: 'a paragraph opened right under an ATX heading still underlines',
    content: '# ATX\nSome para\n---\n',
    anchors: ['atx', 'some-para'],
    markdownBlocks: [],
  },
  {
    name: 'thematic-break',
    why: '`---` after a BLANK line is a thematic break, not a setext underline',
    content: '# Doc\n\n---\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'fence-in-list',
    why: 'a fence opened on the list-marker line hides its `#` lines',
    content: '# Doc\n\n- ```sh\n  # not heading\n  ```\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'fence-in-bq',
    why: 'a fence inside a blockquote hides its `#` lines',
    content: '# Doc\n\n> ```sh\n> # not heading\n> ```\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'dup-list-vs-doc',
    why: 'a list-item heading takes part in the skip-until-free duplicate rule',
    content: '## Foo\n\n- ## Foo\n\n## Foo\n',
    anchors: ['foo', 'foo-1', 'foo-2'],
    markdownBlocks: [],
  },
  {
    name: 'html-anchor-in-div',
    why: 'an explicit anchor inside a <div> block IS served',
    content: '<div>\n<a name="in-div"></a>\n</div>\n\n# Real\n',
    anchors: ['in-div', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'html-anchor-in-cmt',
    why: '...but one inside a comment is not',
    content: '<!--\n<a name="in-cmt"></a>\n-->\n\n# Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'setext-in-list',
    why: 'a setext heading inside a list item',
    content: '- Some para\n  ---\n\n## Real\n',
    anchors: ['some-para', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'atx-closing-hashes',
    why: 'closing `#`s are stripped, in a list item too',
    content: '# Doc #\n\n- ## In List ##\n',
    anchors: ['doc', 'in-list'],
    markdownBlocks: [],
  },
  {
    name: 'list-atx-tab',
    why: 'a TAB after the list marker advances to the 4-column stop',
    content: '-\t# Tab Marker\n\n## Real\n',
    anchors: ['tab-marker', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'bq-no-space',
    why: 'the space after `>` is optional',
    content: '>## No Space Quoted\n\n## Real\n',
    anchors: ['no-space-quoted', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'html-para-tag7',
    why: 'a type-7 tag cannot interrupt a paragraph, so the anchor is paragraph HTML',
    content: 'Some text\n<a name="x"></a>\n\n# Real\n',
    anchors: ['x', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'anchor-in-script',
    why: 'an explicit anchor inside <script> is still served',
    content: '<script>\n<a name="in-script"></a>\n</script>\n\n# Real\n',
    anchors: ['in-script', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'anchor-in-pre',
    why: '...and inside <pre>',
    content: '<pre>\n<a name="in-pre"></a>\n</pre>\n\n# Real\n',
    anchors: ['in-pre', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'heading-in-pre',
    why: 'a heading inside <pre> is not a heading',
    content: '<pre>\n## In Pre\n</pre>\n\n## Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'html-span-type7',
    why: 'a lone <span> after a blank line IS a type-7 block, and swallows the heading under it',
    content: '<span>\n## In Span\n</span>\n\n## Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'html-type7-interrupt',
    why: '...but the same line after a paragraph is paragraph text, so the heading survives',
    content: 'Some text\n<span>\n## After Span\n\n## Real\n',
    anchors: ['after-span', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'html-close-tag-6',
    why: 'a CLOSING type-6 tag opens a block too',
    content: '</div>\n## After Close\n\n## Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'html-decl-type4',
    why: 'a type-4 declaration ends on its own line',
    content: '<!DOCTYPE html>\n## After Decl\n\n## Real\n',
    anchors: ['after-decl', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'html-cdata-type5',
    why: 'a type-5 CDATA block ends at `]]>`',
    content: '<![CDATA[\n## In Cdata\n]]>\n\n## Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'html-pi-type3',
    why: 'a type-3 processing instruction ends at `?>`',
    content: '<?php\n## In Pi\n?>\n\n## Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'html-in-bq',
    why: 'an HTML block inside a blockquote',
    content: '> <div>\n> ## In Div In Bq\n> </div>\n\n## Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'html-in-list',
    why: 'an HTML block inside a list item',
    content: '- <div>\n  ## In Div In List\n  </div>\n\n## Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'html-indented4',
    why: 'a <div> indented 4 is indented code, not an HTML block',
    content: '# Doc\n\n    <div>\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'html-div-oneline',
    why: 'a type-6 block swallows the rest of its opening line',
    content: '# Doc\n\n<div>## Same Line</div>\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'html-comment-inline',
    why: '...and a type-2 comment swallows the rest of the line after `-->`',
    content: '# Doc\n\n<!-- c --> ## After Comment\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'dup-collision-mix',
    why: 'the skip-until-free rule across document, list and blockquote headings at once',
    content: '## Foo\n\n- ## Foo 1\n\n> ## Foo\n\n## Foo\n',
    anchors: ['foo', 'foo-1', 'foo-2', 'foo-3'],
    markdownBlocks: [],
  },
  {
    name: 'setext-then-html',
    why: 'a type-6 tag INTERRUPTS a paragraph, so the `---` under it underlines nothing',
    content: 'Para\n<div>\n---\n\n## Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'atx-no-space',
    why: '`#NoSpace` is not a heading',
    content: '#NoSpace\n\n## Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'atx-hash-only',
    why: 'a bare `#` anchors nothing',
    content: '#\n\n## Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'atx-7-hashes',
    why: 'seven `#` is not a heading',
    content: '####### Seven\n\n## Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'setext-list-interrupt',
    why: 'a list marker interrupts the paragraph, and the `---` at column 0 then closes the item',
    content: 'Some para\n- item\n---\n\n## Real\n',
    anchors: ['real'],
    markdownBlocks: [],
  },
  {
    name: 'setext-bq-lazy',
    why: "a LAZY continuation line keeps the blockquote's paragraph open",
    content: '> Para\nline two\n> ---\n\n## Real\n',
    anchors: ['paraline-two', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'setext-3-lines',
    why: 'three paragraph lines under one `===`',
    content: 'a\nb\nc\n===\n',
    anchors: ['abc'],
    markdownBlocks: [],
  },
  {
    name: 'fence-in-list-marker',
    why: 'a fence opened on the list-marker line, prose after it',
    content: '# Doc\n\n- ```sh\n  # not heading\n  ```\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'html-inside-fence',
    why: 'a <div> inside a fence opens no HTML block',
    content: '# Doc\n\n```html\n<div>\n</div>\n```\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'fence-inside-html',
    why: 'a fence inside a <div> block opens no fence',
    content: '# Doc\n\n<div>\n```\n## In Fence In Div\n```\n</div>\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'setext-dash-in-list',
    why: "a setext heading at the item's content column",
    content: '- a\n\n  Some para\n  ---\n\n## Real\n',
    anchors: ['some-para', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'anchor-id-attr',
    why: '`<a id>` is an anchor too',
    content: '<a id="by-id"></a>\n\n# Real\n',
    anchors: ['by-id', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'html-details-nolank',
    why: '<details>/<summary> with no blank line swallows the heading',
    content: '# Doc\n\n<details>\n<summary>s</summary>\n## No Blank\n</details>\n\n## Real\n',
    anchors: ['doc', 'real'],
    markdownBlocks: [],
  },
  {
    name: 'fence-layout-1',
    why: 'a ```markdown mentioned MID-PROSE opens nothing — the guide ships no snippet',
    content:
      'Open the block with ```markdown so the reader can copy it, then close it.\n\nSome prose in between.\n\nLater, some inline code: ``` is the fence marker.\n',
    anchors: [],
    markdownBlocks: [],
  },
  {
    name: 'fence-layout-2',
    why: 'opener indented 3 spaces is still a fence',
    content: '   ```markdown\n# Way of Working\n   ```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-layout-3',
    why: 'opener indented 4 spaces is an INDENTED CODE BLOCK, not a fence',
    content: '    ```markdown\n# Way of Working\n    ```\n',
    anchors: ['way-of-working'],
    markdownBlocks: [],
  },
  {
    name: 'fence-layout-4',
    why: 'closer indented 3 spaces closes',
    content: '```markdown\n# Way of Working\n   ```\n\nafter\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-layout-5',
    why: 'closer indented 4 spaces does NOT close — the block runs to EOF',
    content: '```markdown\n# Way of Working\n    ```\n\nafter\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n    ```\n\nafter\n'],
  },
  {
    name: 'fence-layout-6',
    why: 'a ``` mid-prose does NOT close — the block runs to EOF',
    content: '```markdown\n# Way of Working\nthen ``` closes it.\n\nafter\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\nthen ``` closes it.\n\nafter\n'],
  },
  {
    name: 'fence-layout-7',
    why: 'an unclosed fence runs to EOF, and its snippet must still be seen',
    content: '```markdown\n# Way of Working\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-layout-8',
    why: 'whitespace between the fence and the info string',
    content: '``` markdown\n# Way of Working\n```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-layout-9',
    why: 'a ```markdown line INSIDE an open ```bash fence opens nothing — a heredoc example, not a copy-paste surface',
    content: '```bash\ncat <<EOF\n```markdown\n# Way of Working\n```\nEOF\n```\n',
    anchors: [],
    markdownBlocks: [],
  },
  {
    name: 'fence-layout-10',
    why: 'a ```markdown line inside an open ~~~ fence opens nothing either',
    content: '~~~text\n```markdown\n# Way of Working\n```\n~~~\n',
    anchors: [],
    markdownBlocks: [],
  },
  {
    name: 'fence-layout-11',
    why: 'a closer bearing an INFO STRING does not close — the ```bash line stays inside the block',
    content: '```markdown\n# Way of Working\n```bash\nstill inside per CommonMark\n```\n\nafter\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n```bash\nstill inside per CommonMark\n'],
  },
  {
    name: 'fence-layout-12',
    why: 'a closer LONGER than the opener closes',
    content: '```markdown\n# Way of Working\n`````\n\nafter\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-layout-13',
    why: 'a closer of the OTHER fence char does not close — the block runs to EOF',
    content: '```markdown\n# Way of Working\n~~~\n\nafter\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n~~~\n\nafter\n'],
  },
  {
    name: 'fence-layout-14',
    why: 'a BACKTICK inside a backtick fence’s info string is not a fence opener at all',
    content: '```markdown `x`\n# Way of Working\n```\n',
    anchors: ['way-of-working'],
    markdownBlocks: [],
  },
  {
    name: 'fence-layout-15',
    why: '...but a TILDE fence may carry backticks in its info string',
    content: '~~~markdown `x`\n# Way of Working\n~~~\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-layout-16',
    why: 'a closer with trailing whitespace still closes',
    content: '```markdown\n# Way of Working\n```   \n\nafter\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-1',
    why: 'a fence inside a BLOCKQUOTE is a fence, and its body loses the `> ` prefix',
    content: '> ```markdown\n> # Way of Working\n>\n> - `pm-tool`: linear\n> ```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n\n- `pm-tool`: linear\n'],
  },
  {
    name: 'fence-container-2',
    why: 'an unclosed blockquoted fence runs to EOF',
    content: '> ```markdown\n> # Way of Working\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-3',
    why: 'a blank line ends the blockquote, and with it the fence',
    content: '> ```markdown\n> # Way of Working\n\nafter\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-4',
    why: 'a LAZY continuation line (no `>`) stays inside the blockquoted fence',
    content: '> ```markdown\n> # Way of Working\nlazy line\n> ```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-5',
    why: 'a closer OUTSIDE the blockquote does not close it — the blockquote end does',
    content: '> ```markdown\n> # Way of Working\n```\n\nafter\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-6',
    why: 'blockquote nested twice: both markers are peeled, neither is body',
    content: '> > ```markdown\n> > # Way of Working\n> > ```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-7',
    why: 'the space after `>` is optional',
    content: '>```markdown\n># Way of Working\n>```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-8',
    why: 'tilde fence inside a blockquote',
    content: '> ~~~markdown\n> # Way of Working\n> ~~~\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-9',
    why: 'the run-length rule holds inside a blockquote: a shorter run is body',
    content: '> ````markdown\n> # Way of Working\n> ```\n> still inside\n> ````\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n```\nstill inside\n'],
  },
  {
    name: 'fence-container-10',
    why: 'the info-string rule holds inside a blockquote: a ```bash line does not close',
    content: '> ```markdown\n> # Way of Working\n> ```bash\n> still inside\n> ```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n```bash\nstill inside\n'],
  },
  {
    name: 'fence-container-11',
    why: 'a ```markdown line inside a blockquoted ```bash fence opens nothing',
    content: '> ```bash\n> cat <<EOF\n> ```markdown\n> # Way of Working\n> ```\n> EOF\n> ```\n',
    anchors: [],
    markdownBlocks: [],
  },
  {
    name: 'fence-container-12',
    why: 'a `>` line in the BODY of a blockquoted fence is body, not a third marker',
    content: '> ```markdown\n> > quoted line in body\n> ```\n',
    anchors: [],
    markdownBlocks: ['> quoted line in body\n'],
  },
  {
    name: 'fence-container-13',
    why: 'a `>` line inside a DOCUMENT-level fence is body — the reader peels no marker it did not open with',
    content: '```markdown\n# Way of Working\n> not a blockquote marker\n```\n\nafter\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n> not a blockquote marker\n'],
  },
  {
    name: 'fence-container-14',
    why: 'a list inside a blockquote: both containers are stripped',
    content: '> - a\n>\n>   ```markdown\n>   # Way of Working\n>   ```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-15',
    why: 'a fence in a LIST ITEM is a fence, and its body loses the item indentation',
    content: '- a\n\n  ```markdown\n  # Way of Working\n  ```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-16',
    why: 'a fence in a NESTED list item, indented 4+, is a fence and not an indented code block',
    content: '- a\n  - b\n\n    ```markdown\n    # Way of Working\n    ```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-17',
    why: 'a fence opened on the list-marker line itself',
    content: '- ```markdown\n  # Way of Working\n  ```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-18',
    why: 'an ORDERED list item content column',
    content: '1. a\n\n   ```markdown\n   # Way of Working\n   ```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-19',
    why: 'inside a list item the 3-space rule is RELATIVE to the content column: 2 extra is still a fence',
    content: '- a\n\n    ```markdown\n    # Way of Working\n    ```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-20',
    why: '...and 4 extra is an indented code block inside the item, not a fence',
    content: '- a\n\n      ```markdown\n      # Way of Working\n      ```\n',
    anchors: [],
    markdownBlocks: [],
  },
  {
    name: 'fence-container-21',
    why: '5+ spaces after the marker start an indented code block, so the fence line opens nothing',
    content: '-     ```markdown\n  # Way of Working\n  ```\n',
    anchors: ['way-of-working'],
    markdownBlocks: [],
  },
  {
    name: 'fence-container-22',
    why: 'a body line left of the content column ends the item, and with it the fence',
    content: '- a\n\n  ```markdown\n  # Way of Working\nback at column 0\n  ```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-23',
    why: 'a blank line inside a list-item fence does NOT end it',
    content: '- a\n\n  ```markdown\n  # Way of Working\n\n  - `pm-tool`: linear\n  ```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n\n- `pm-tool`: linear\n'],
  },
  {
    name: 'fence-container-24',
    why: 'a fence at column 0 after a list item belongs to the document, not the item',
    content: '- a\n\n```markdown\n# Way of Working\n```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-25',
    why: 'a document-level fence after a blockquote',
    content: '> quoted\n\n```markdown\n# Way of Working\n```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-26',
    why: 'a TAB-indented list item: the tab is 4 columns, so the fence is at the content column',
    content: '-\ta\n\n\t```markdown\n\t# Way of Working\n\t```\n',
    anchors: [],
    markdownBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-27',
    why: '...and only the columns the opener consumed are stripped: the body keeps its own tab',
    content: '-\ta\n\n\t```markdown\n\t\t# Way of Working\n\t```\n',
    anchors: [],
    markdownBlocks: ['\t# Way of Working\n'],
  },
  {
    name: 'fence-container-28',
    why: 'a tab in the body of a document-level fence is content, never indentation',
    content: '```markdown\n\t# Way of Working\n```\n',
    anchors: [],
    markdownBlocks: ['\t# Way of Working\n'],
  },
  {
    name: 'fence-container-29',
    why: 'a tab-indented fence at document level is an indented code block (4 columns)',
    content: '\t```markdown\n\t# Way of Working\n\t```\n',
    anchors: [],
    markdownBlocks: [],
  },
  {
    name: 'fence-container-30',
    why: "TAB directly after `>`: the COUNT is github's, but the body is one leading space short of it — cmark splits that tab between the marker and the content, this reader gives the whole remainder to the content",
    content: '>\t```markdown\n>\t# Way of Working\n>\t```\n',
    anchors: [],
    markdownBlocks: [' # Way of Working\n'],
    // cmark splits the tab after `>` between the marker and the content; this reader
    // gives the whole remainder to the content, so the body is one leading space short.
    readerBlocks: ['# Way of Working\n'],
  },
  {
    name: 'fence-container-31',
    why: 'a fence inside an HTML COMMENT: github renders no block (the comment is an HTML block, CommonMark § 4.6), this reader still sees one — over-reporting, so a guide hiding a snippet there is asked to classify it, never silently passed',
    content: '<!--\n```markdown\n# Way of Working\n```\n-->\n',
    anchors: [],
    markdownBlocks: [],
  },
  {
    name: 'fence-container-32',
    why: 'same for a raw <div> block: over-reported, never under-reported',
    content: '<div>\n```markdown\n# Way of Working\n```\n</div>\n',
    anchors: [],
    markdownBlocks: [],
  },
  {
    name: 'fence-container-33',
    why: 'same for the <details>/<summary> pattern the KB uses for collapsed sections',
    content: '<details>\n<summary>s</summary>\n```markdown\n# Way of Working\n```\n</details>\n',
    anchors: [],
    markdownBlocks: [],
  },
  {
    name: 'inline-codespan-html',
    why: 'a CODE SPAN is literal text: `<issue-id>` inside one is not inline HTML (3 live files carry this heading)',
    content: '### `--root <issue-id>` — subtree scope\n',
    anchors: ['--root-issue-id--subtree-scope'],
    markdownBlocks: [],
  },
  {
    name: 'inline-html-outside',
    why: '...while the same tag OUTSIDE a code span is stripped',
    content: '## A <span>tag</span> here\n\n## Mixed `<code>` and <b>bold</b>\n',
    anchors: ['a-tag-here', 'mixed-code-and-bold'],
    markdownBlocks: [],
  },
  {
    name: 'inline-codespan-link',
    why: 'a link WRAPPING a code span still resolves to its text',
    content: '## [`Templates`](t/README.md) link\n\n## [Plain](x.md) link\n',
    anchors: ['templates-link', 'plain-link'],
    markdownBlocks: [],
  },
  {
    name: 'inline-codespan-literal-link',
    why: '...but a link INSIDE a code span is literal: the brackets go, the letters stay',
    content: '## `[a](b)` link in code\n',
    anchors: ['ab-link-in-code'],
    markdownBlocks: [],
  },
  {
    name: 'inline-codespan-emphasis',
    why: 'underscores survive inside a code span; `_em_` outside it is markup',
    content: '## `*star*` and *star*\n\n## `_snake_case_` and _em_\n',
    anchors: ['star-and-star', '_snake_case_-and-em'],
    markdownBlocks: [],
  },
  {
    name: 'inline-codespan-nested',
    why: 'a longer delimiter run holds a backtick; a stray unmatched backtick is just dropped',
    content: '## ``a ` b`` tick\n\n## un`closed span\n',
    anchors: ['a--b-tick', 'unclosed-span'],
    markdownBlocks: [],
  },
  {
    name: 'inline-html-trailing-space',
    why: "the space a stripped tag leaves behind is NOT trimmed — the trailing `-` is github's",
    content: '## `<x>` vs <x>\n',
    anchors: ['x-vs-'],
    markdownBlocks: [],
  },
  {
    name: 'html-id-attributes',
    why: "an explicit anchor is ANY tag's id, quoted or bare — CAP: the raw <h2>'s own text (`h`) is not read",
    content:
      '<div id="div-id">x</div>\n\n<h2 id="h2-id">H</h2>\n\nInline <span id="span-id">s</span> here.\n\n<img src="a.png" id="img-id">\n\n<div id=\'single-quoted\'>y</div>\n\n<div id=unquoted>z</div>\n\n# Real\n',
    anchors: ['div-id', 'h2-id', 'h', 'span-id', 'img-id', 'single-quoted', 'unquoted', 'real'],
    markdownBlocks: [],
    readerAnchors: ['div-id', 'h2-id', 'span-id', 'img-id', 'single-quoted', 'unquoted', 'real'],
  },
  {
    name: 'html-name-map',
    why: "CAP: github's sanitizer drops <map> entirely, so its name anchors nothing; this reader still emits it (over-report)",
    content: '<map name="map-name"></map>\n\n# Real\n',
    anchors: ['real'],
    markdownBlocks: [],
    readerAnchors: ['map-name', 'real'],
  },
  {
    name: 'html-raw-heading',
    why: 'CAP: a RAW HTML heading is an anchor on github.com; this reader does not parse inline HTML headings (under-report)',
    content: '<h3>Raw H3</h3>\n\n# Real\n',
    anchors: ['raw-h3', 'real'],
    markdownBlocks: [],
    readerAnchors: ['real'],
  },
  {
    name: 'html-id-continuation-line',
    why: "an id on a CONTINUATION line of a multi-line raw tag is still that tag's anchor \u2014 the shape `framework-patterns/components.md` ships, and the reason an HTML block is scanned joined, not line by line",
    content: '<div\n  role="tabpanel"\n  id={`panel-${value}`}\n>\nx\n</div>\n\n# Real\n',
    anchors: ['{`panel-${value}`}', 'real'],
    markdownBlocks: [],
  },
]
