import type { KbHost, KbIdentity } from '../identity'

/** Where the generated script writes the packaged ZIP (shell form, `$VERSION` unexpanded). */
export function releaseZipPath(identity: KbIdentity): string {
  return 'dist/' + identity.slug + '-$VERSION.zip'
}

/** Human-facing form of the ZIP path, for documentation. */
export function releaseZipPattern(identity: KbIdentity): string {
  return `dist/${identity.slug}-<version>.zip`
}

function header(identity: KbIdentity): string[] {
  return [
    '#!/usr/bin/env bash',
    '#',
    `# Release script for ${identity.name} — generated by \`pair-cli scaffold-kb\`.`,
    '#',
    '# Packaging is delegated entirely to `pair package`: this script only maps a',
    '# version to a ZIP and (on GitHub) to a tag + release. No separate release',
    '# mechanism, so the KB ZIP is byte-for-byte what `pair install` already understands.',
    '#',
    '# Usage: bash scripts/release.sh <version>      # e.g. bash scripts/release.sh 1.0.0',
    '# Env:   PAIR_CLI — how pair-cli is invoked (default: npx --yes @foomakers/pair-cli)',
    '',
    'set -euo pipefail',
    '',
  ]
}

function packagingSteps(identity: KbIdentity): string[] {
  return [
    'VERSION="${1:-}"',
    "if ! printf '%s' \"$VERSION\" | grep -Eq '^[0-9]+\\.[0-9]+\\.[0-9]+([-+][0-9A-Za-z.-]+)?$'; then",
    '  echo "usage: bash scripts/release.sh <version>   (semver, e.g. 1.0.0)" >&2',
    '  exit 1',
    'fi',
    '',
    'PAIR_CLI="${PAIR_CLI:-npx --yes @foomakers/pair-cli}"',
    `ZIP="${releaseZipPath(identity)}"`,
    '',
    `echo "==> Packaging ${identity.name} v$VERSION"`,
    '$PAIR_CLI package \\',
    '  -s . \\',
    '  --layout source \\',
    `  --name "${identity.name}" \\`,
    '  --pkg-version "$VERSION" \\',
    '  -o "$ZIP"',
    '',
    'echo "==> Packaged: $ZIP"',
    '',
  ]
}

function manualPublishNotice(): string[] {
  return [
    '  echo "    Your KB package is ready at $ZIP — publish it however your org does:"',
    '  echo "    attach it to a release, upload it to an artifact store, or serve it over HTTP."',
    '  echo "    Consumers install it with: pair-cli install --source <url-or-path-of-the-zip>"',
  ]
}

function githubPublishSteps(identity: KbIdentity): string[] {
  return [
    'if ! command -v gh >/dev/null 2>&1 || ! git rev-parse --is-inside-work-tree >/dev/null 2>&1; then',
    '  echo "==> No gh CLI or no git repository here — skipping tag and GitHub release."',
    ...manualPublishNotice(),
    '  exit 0',
    'fi',
    '',
    'if git rev-parse -q --verify "refs/tags/v$VERSION" >/dev/null; then',
    '  echo "==> Tag v$VERSION already exists — skipping tag creation"',
    'else',
    `  git tag -a "v$VERSION" -m "${identity.name} v$VERSION"`,
    '  git push origin "v$VERSION"',
    'fi',
    '',
    'if gh release view "v$VERSION" >/dev/null 2>&1; then',
    '  echo "==> Release v$VERSION already exists — uploading the ZIP"',
    '  gh release upload "v$VERSION" "$ZIP" --clobber',
    'else',
    `  gh release create "v$VERSION" "$ZIP" --title "${identity.name} v$VERSION" \\`,
    `    --notes "${identity.name} knowledge base v$VERSION. Install with: pair-cli install --source <zip-url>"`,
    'fi',
    '',
    'echo "==> Released v$VERSION"',
    '',
  ]
}

function genericPublishSteps(): string[] {
  return [
    '# No code-host automation on this host: the ZIP is the deliverable.',
    'echo "==> Packaging done — no automated release publishing configured for this host."',
    ...manualPublishNotice().map(line => line.replace(/^ {2}/, '')),
    '',
  ]
}

/**
 * Render the release script for a scaffolded KB repo.
 *
 * GitHub is the primary target (tag + release with the ZIP attached); every other
 * host degrades gracefully to "here is your ZIP, publish it however your org does",
 * which keeps `pair-cli` itself code-host agnostic — publishing never lives in the CLI.
 */
export function renderReleaseScript(options: { identity: KbIdentity; host: KbHost }): string {
  const { identity, host } = options
  const publish = host === 'github' ? githubPublishSteps(identity) : genericPublishSteps()

  return [...header(identity), ...packagingSteps(identity), ...publish].join('\n')
}
