import { describe, it, expect } from 'vitest'
import { readFileSync } from 'fs'
import { join } from 'path'
import { fileSystemService } from '@pair/content-ops'
import { generateLlmsTxt } from './llms-generation'

// `.pair/llms.txt` is GENERATED by `pair install` / `pair update` (generateLlmsTxt
// below), but it is also CHECKED IN — this repo dogfoods its own KB, so the index
// every agent reads is the committed file, not a build artifact. Nothing pinned the
// two together: `llms-generation.test.ts` runs the generator over in-memory
// fixtures, so a KB file added by hand (or one the generator would list and nobody
// added) drifts the committed index silently. That had already happened — the
// review of #216 found `story-local-markers.md` present in the KB tree and absent
// from the index on both the branch and `main`, invisible to every agent reading it.
//
// This guard is the missing equality: run the REAL generator over the REAL repo
// tree and compare byte-for-byte with the committed file. It re-uses the production
// `generateLlmsTxt` (no parallel implementation), so a generator change and a KB
// change both surface here.

const REPO_ROOT = join(__dirname, '../../../..')

describe('.pair/llms.txt — the committed index equals the generator over the repo tree', () => {
  it('matches `generateLlmsTxt` byte-for-byte', async () => {
    const generated = await generateLlmsTxt(fileSystemService, REPO_ROOT)
    const committed = readFileSync(join(REPO_ROOT, '.pair/llms.txt'), 'utf-8')

    expect(committed).toBe(generated)
  })

  it('indexes the automation policy shipped by #216', async () => {
    const generated = await generateLlmsTxt(fileSystemService, REPO_ROOT)

    expect(generated).toContain(
      '(.pair/knowledge/guidelines/collaboration/automation/automation-policy.md)',
    )
  })
})
