import { describe, it, expect } from 'vitest'
import { readFileSync } from 'fs'
import { join } from 'path'
import { fileSystemService } from '@pair/content-ops'
import { generateLlmsTxt } from './llms-generation'

// `.pair/llms.txt` is GENERATED by `pair-cli install` / `pair-cli update` (generateLlmsTxt
// below), but it is also CHECKED IN — this repo dogfoods its own KB, so the index
// every agent reads is the committed file, not a build artifact. Nothing pinned the
// two together: `llms-generation.test.ts` runs the generator over in-memory
// fixtures, so a KB file added by hand (or one the generator would list and nobody
// added) drifts the committed index silently. That had already happened — the
// review of #216 found `story-local-markers.md` present in the KB tree and absent
// from the index on both the branch and `main`, invisible to every agent reading it.
//
// This guard is the missing equality: run the REAL generator over the REAL repo
// tree and compare byte-for-byte with the committed file. It re-uses the production
// `generateLlmsTxt` (no parallel implementation), so a generator change and a KB
// change both surface here.
//
// OVERLAPS #416 ("tech-debt: no gate covers .pair/llms.txt drift"), which owns this
// coverage properly. What lands here is #416's AC1 only — the byte-for-byte
// comparison — reached through `turbo test` (root `quality-gate` + ci.yml). What
// #416 still owns: an actionable failure message (the missing/extra lines, not a
// raw vitest diff over a 400-line file), naming the command that regenerates the
// index, fixture-tree + determinism tests, and MOVING the check to
// `packages/dev-tools/src/quality-gates` so gate composition stays uniform. Do not
// duplicate this file there — replace it.

const REPO_ROOT = join(__dirname, '../../../..')

describe('.pair/llms.txt — the committed index equals the generator over the repo tree', () => {
  it('matches `generateLlmsTxt` byte-for-byte', async () => {
    const generated = await generateLlmsTxt(fileSystemService, REPO_ROOT)
    const committed = readFileSync(join(REPO_ROOT, '.pair/llms.txt'), 'utf-8')

    expect(committed).toBe(generated)
  })

  // The generator scanned `.pair/product/adopted` / `.pair/tech/adopted` —
  // directories no shipped dataset ever created — so the index every agent reads
  // to find project context carried NO Adoption sections at all: an adopting
  // project ran `pair-cli install` and got an llms.txt missing its own PRD,
  // architecture and tech-stack, the highest-value entries in the file, with
  // nothing reporting it. Byte equality above pins whatever the generator emits,
  // so without this case the wrong output would be asserted correct.
  it('indexes the project adoption files from the real layout', async () => {
    const generated = await generateLlmsTxt(fileSystemService, REPO_ROOT)

    expect(generated).toContain('## Adoption — Product')
    expect(generated).toContain('## Adoption — Tech')
    expect(generated).toContain('(.pair/adoption/tech/tech-stack.md)')
    expect(generated).toContain('(.pair/adoption/tech/architecture.md)')
    expect(generated).toContain('(.pair/adoption/product/PRD.md)')
    expect(generated).not.toMatch(/\.pair\/(product|tech)\/adopted/)
  })

  // 50 ADL / analysis entries live in `.pair/adoption/decision-log/` and were
  // reachable from no section, while `adoption/tech/adr/**` was indexed — so the
  // index presented this project's decision record as ADR-only. Concrete failure:
  // an agent reads `.pair/llms.txt` (the index this story exists to repair) looking
  // for why eligibility is one literal label, and neither
  // `2026-08-20-eligibility-is-one-literal-label-until-the-filter-widens.md` nor
  // `2026-08-20-eligibility-schema-lives-in-collaboration-automation.md` is listed.
  it('indexes the decision log, not just the ADRs', async () => {
    const generated = await generateLlmsTxt(fileSystemService, REPO_ROOT)

    expect(generated).toContain('## Adoption — Decisions')
    expect(generated).toContain(
      '(.pair/adoption/decision-log/2026-08-20-eligibility-is-one-literal-label-until-the-filter-widens.md)',
    )
  })

  it('indexes the automation policy shipped by #216', async () => {
    const generated = await generateLlmsTxt(fileSystemService, REPO_ROOT)

    expect(generated).toContain(
      '(.pair/knowledge/guidelines/collaboration/automation/automation-policy.md)',
    )
  })
})
